### ISSUE TITLE
set-env is disabled on github now

### ISSUE THREAD

**Issue by ryancole** [Azure/functions-container-action#10]
Getting the following error ...

```
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

/cc: @AmrutaKawade @SumiranAgg @N-Usha

**Comment by aksm-ms** [comment]
@ryancole can you please send your workflow? Please verify if you are using azure/functions-container-action@v1

**Comment by ryancole** [comment]
@aksm-ms sure, no problem. Here's my workflow step that does the function deploy ...

```yaml
      - uses: Azure/functions-container-action@v1.0.1
        with:
          image: xxx.azurecr.io/wib-workspace-functions:${{ github.event.release.tag_name }}
          app-name: xxx
```

So, I'm using v1.0.1
