### ISSUE TITLE
Azure/functions-container-action@v1 - TypeError: Cannot read property 'getApplicationURL'

### ISSUE THREAD

**Issue by bgarcial** [Azure/functions-container-action#12]
I have an azure function (python code) containerized in a Dockerfile. I want to run it from Github actions, so I am doing in my workflow the following:

```

    - name: 'Run Azure Functions Container Action'
      uses: Azure/functions-container-action@v1
      id: fa
      with:
        app-name: my-spec-prod-azure-function
        image: containerregistry.azurecr.io/my-azure-function:latest

    - name: Azure logout
      run: |
        az logout
```

The thing here is I am using `Azure/functions-container-action@v1` github action to run the container but it does not work, I got the following message error in my pipeline:

```
Run Azure/functions-container-action@v1
  with:
    app-name: my-spec-prod-azure-function
    image: containerregistry.azurecr.io/my-azure-function:latest
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    DOCKER_CONFIG: /home/runner/work/_temp/docker_login_1613723968334
Error: Error: Resource my-spec-prod-azure-function doesn't exist.
(node:4655) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getApplicationURL' of undefined
    at /home/runner/work/_actions/Azure/functions-container-action/v1/lib/main.js:68:68
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/Azure/functions-container-action/v1/lib/main.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4655) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4655) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Checking the azure actions workflow samples, [you also use the same action][1] (`Azure/functions-container-action@v1`) to deploy an azure function, they emphasize that [here][2]. 

Here someone [got a similar error description][3] but I am afraid it is not for azure functions container but for appservices actions that use containers. Despite that, I also tried the `azure/webapps-container-deploy@v1` action but it does not work, and I think that is not a suited action. 

I checked [your official marketplace site][4] and you say this is the latest version to use:
```
- name: Azure Functions Container Action
  uses: Azure/functions-container-action@v1.0.1
```

So I changed `Azure/functions-container-action@v1` by `Azure/functions-container-action@v1.0.1`
without success, I got a very similar error but with some hints or clue about setting environment variables.

```
Error: Unable to process command '::set-env name=AZURE_HTTP_USER_AGENT,::GITHUBACTIONS_DeployFunctionAppContainerToAzure_b32b908e01efeb4da360da24648fd5091bc18dcc93090b9c05ee3b76efe9b57e' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
Error: Error: Resource my-spec-prod-azure-function doesn't exist.
(node:4508) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getApplicationURL' of undefined
    at /home/runner/work/_actions/Azure/functions-container-action/v1.0.1/lib/main.js:68:68
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/Azure/functions-container-action/v1.0.1/lib/main.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Regarding the `The set-env command is disabled` new error message, checking the log changes, [here][5] is not clear for me how or why the env variables like  `AZURE_HTTP_USER_AGENT` and the other one should be set it up properly.
 

  [1]: https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-container-functionapp-on-azure.yml#L44
  [2]: https://github.com/Azure/functions-container-action#create-azure-function-app-and-deploy-to-function-app-container-using-github-actions
  [3]: https://github.com/Azure/appservice-actions/issues/5#issuecomment-548737388
  [4]: https://github.com/marketplace/actions/azure-functions-container-action
  [5]: http://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands

**Comment by N-Usha** [comment]
@Hazhzeng - Can you please look into this issue?

**Comment by bgarcial** [comment]
Thanks @N-Usha and @Hazhzeng 

I wanted to come up with a kind of workaround I have been trying

**UPDATE**

Regarding  the `The set-env command is disabled` new error message, checking the changes announced, [here](http://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands), I can see: 

>Action authors who are using the toolkit should update the @actions/core package to v1.2.6 or greater to get the updated addPath and exportVariable functions

I am not an actions author, but I wanted to try to update/install the @actions/core package to `v1.2.6` into the github hosted runner I am using in the pipeline, so my YAML file definition has now these steps:

```
- name: 'Setting node environment to get npm command'
      # uses: actions/checkout@v2
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '12'

    - name: 'Installing @actions/core latest version'
      # uses: @actions/core
      # with:
        # version: 1.2.6
      run: |
        npm install @actions/core
        # SETTING UP AZURE_HTTP_USER_AGENT to GITHUB_ENV
        echo "name=${AZURE_HTTP_USER_AGENT}" >> $GITHUB_ENV

    - name: 'Run Azure Functions Container Action'
      uses: Azure/functions-container-action@v1.0.1
      id: fa
      with:
        app-name: my-spec-prod-azure-function
        image: containerregistry.azurecr.io/my-azure-function:latest

    - name: Azure logout
      run: |
        az logout
```

In addition, I added to my repository the following files:
 
- `package.json`

```
{
  "name": "my-project",
  "version": "1.0.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/user-org/my-project.git"
  },
  "dependencies": {
    "@actions/core": "^1.2.6"
  }
}

```   

- `package-lock.json`

```
{
  "name": "my-project",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "packages": {
    "": {
      "version": "1.0.0",
      "dependencies": {
        "@actions/core": "^1.2.6"
      }
    },
    "node_modules/@actions/core": {
      "version": "1.2.6",
      "resolved": "https://registry.npmjs.org/@actions/core/-/core-1.2.6.tgz",
      "integrity": "sha512-ZQYitnqiyBc3D+k7LsgSBmMDVkOVidaagDG7j3fOym77jNunWRuYx7VSHa9GNfFZh+zh61xsCjRj4JxMZlDqTA=="
    }
  },
  "dependencies": {
    "@actions/core": {
      "version": "1.2.6",
      "resolved": "https://registry.npmjs.org/@actions/core/-/core-1.2.6.tgz",
      "integrity": "sha512-ZQYitnqiyBc3D+k7LsgSBmMDVkOVidaagDG7j3fOym77jNunWRuYx7VSHa9GNfFZh+zh61xsCjRj4JxMZlDqTA=="
    }
  }
}
```
I can see `@actions/core` package is being added to my workflow here:

- **Setting node environment to get npm command step**
```
Run actions/setup-node@v2.1.4
  with:
    node-version: 12
    always-auth: false
    check-latest: false
    token: ***
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    DOCKER_CONFIG: /home/runner/work/_temp/docker_login_1613768385315
Found in cache @ /opt/hostedtoolcache/node/12.20.2/x64
```

- **Installing `@actions/core` latest version step**

```
Run npm install @actions/core
  npm install @actions/core
  echo "name=$***AZURE_HTTP_USER_AGENT***" >> $GITHUB_ENV
  shell: /usr/bin/bash -e ***0***
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    DOCKER_CONFIG: /home/runner/work/_temp/docker_login_1613768385315
npm WARN fem-downloader@1.0.0 No license field.

+ @actions/core@1.2.6
added 1 package and audited 1 package in 0.524s
found 0 vulnerabilities
```

But at the step when deploying azure function I got the same error gotten before
```
Error: Unable to process command '::set-env name=AZURE_HTTP_USER_AGENT,::GITHUBACTIONS_DeployFunctionAppContainerToAzure_b32b908e01efeb4da360da24648fd5091bc18dcc93090b9c05ee3b76efe9b57e' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands
```

Reading on [here](https://github.community/t/replace-deprecated-set-env/146593/2?u=bgarcial) (also because of the blog post link referenced above) I detailed, the thing is I have to find a different way to set up variables instead of use the deprecated “set-env”. 

It seems behind of scenes `Azure/functions-container-action@v1.0.1` try to use the the deprecated `“set-env”` command. Now is necessary to pass variables into `$GITHUB_ENV` 
[such as GitHub actions docs say it here](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable)

I am trying to do the same with `AZURE_HTTP_USER_AGENT` in this way as you could see above at the immediately previous step before using `Azure/functions-container-action@v1.0.1`:

`echo "name=${AZURE_HTTP_USER_AGENT}" >> $GITHUB_ENV`

But I got the same error. It seems that is not the correct way to do it. Is not clear for me how or why the env variables like  `AZURE_HTTP_USER_AGENT` should be set it up properly with respect to `GITHUB_ENV`


But in more general thinking,  I am in doubt whether is this an issue from [azure functions container action marketplace](https://github.com/marketplace/actions/azure-functions-container-action) or is something I should handle it by attending the GitHub changes env variables discussed 

I would love your thoughts about it.

**Comment by AmrutaKawade** [comment]
We have already upgraded @actions/core version in our action. since you are pointing older version `v1.0.1` its failing for you. latest version id `v1.0.2` or just `v1. set-env error is coming because of this version only.

Now coming back to your first error.
Are you using azure/login action before function-container-action as mentioned [here](https://github.com/Azure/functions-container-action#azure-service-principle-for-rbac)?

**Comment by bgarcial** [comment]
@AmrutaKawade, By the time I filed this issue I tried the `v1` and `v1.0.1` versions and I got the error described above. I also tried these versions right now, without succeed

I didn't know there were a new `v1.0.2` version for this github action. At the marketplace website [the latest referenced version](https://github.com/marketplace/actions/azure-functions-container-action) is `v1.0.1`. 

I pointed up to `v1.0.2` version and I got the same error as well. This one:

```
Run Azure/functions-container-action@v1.0.2
  with:
    app-name: rhd-spec-prod-fem-downloader-function
    image: rhdhvcontainerregistry.azurecr.io/af-fem-downloader:latest
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    DOCKER_CONFIG: /home/runner/work/_temp/docker_login_1613984821988
Error: Error: Resource rhd-spec-prod-fem-downloader-function doesn't exist.
(node:1724) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getApplicationURL' of undefined
    at /home/runner/work/_actions/Azure/functions-container-action/v1.0.2/lib/main.js:68:68
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/Azure/functions-container-action/v1.0.2/lib/main.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am using `azure/login@v1` as a first step before building the container when azure functions live and before deploying it. The azure login and docker steps are successful for me, but not when running the azure functions action container. Here my entire workflow actions:

```
name: Deploy_Workflow

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: containerregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        docker image build --build-arg AZ_DEVOPS_TOKEN="${{ secrets.AZ_DEVOPS_TOKEN }}"  . -t containerregistry.azurecr.io/my-azure-function:latest
        docker push containerregistry.azurecr.io/my-azure-function:latest

    - name: 'Run Azure Functions Container Action'
      uses: Azure/functions-container-action@v1.0.2 
      id: fa
      with:
        app-name: my-spec-prod-azure-function
        image: containerregistry.azurecr.io/my-azure-function:latest

    - name: Azure logout
      run: |
        az logout
```
